export type VariableGroup = 'venue' | 'deal' | 'contact' | 'artist'

export interface VariableCatalogEntry {
  key: string
  label: string
  group: VariableGroup
}

/** Canonical list for slash-menu and docs; keys match {{snake_case}} tokens. */
export const AGREEMENT_VARIABLE_CATALOG: VariableCatalogEntry[] = [
  { key: 'venue_name', label: 'Venue name', group: 'venue' },
  { key: 'city', label: 'City', group: 'venue' },
  { key: 'location', label: 'Street address (line 1)', group: 'venue' },
  { key: 'venue_type', label: 'Venue type (slug)', group: 'venue' },
  { key: 'venue_type_label', label: 'Venue type (label)', group: 'venue' },
  { key: 'event_date', label: 'Event date (long form, Pacific; venue terms or deal)', group: 'venue' },
  { key: 'event_date_iso', label: 'Event date ISO YYYY-MM-DD (when available)', group: 'venue' },
  { key: 'artist_pay', label: 'Artist pay', group: 'venue' },
  { key: 'artist_pay_display', label: 'Artist pay (currency)', group: 'venue' },
  { key: 'set_length', label: 'Set length (venue terms; may match computed set duration)', group: 'venue' },
  { key: 'load_in_time', label: 'Load-in time', group: 'venue' },
  { key: 'notes', label: 'Notes (venue terms)', group: 'venue' },
  { key: 'venue_capacity', label: 'Venue capacity', group: 'venue' },

  { key: 'deal_description', label: 'Deal description', group: 'deal' },
  { key: 'event_name', label: 'Event name (same as deal description)', group: 'deal' },
  { key: 'event_start_time', label: 'Event start time (12h, Pacific)', group: 'deal' },
  { key: 'event_end_time', label: 'Event end time (12h, Pacific)', group: 'deal' },
  { key: 'event_date_display', label: 'Event date (long form, Pacific)', group: 'deal' },
  { key: 'event_window_display', label: 'Event window (readable range, Pacific)', group: 'deal' },
  { key: 'performance_genre', label: 'Performance / set genre', group: 'deal' },
  { key: 'performance_start_time', label: 'Performance set start (12h, Pacific)', group: 'deal' },
  { key: 'performance_end_time', label: 'Performance set end (12h, Pacific)', group: 'deal' },
  { key: 'performance_date_display', label: 'Performance date (long form, Pacific)', group: 'deal' },
  { key: 'performance_window_display', label: 'Performance window (readable range, Pacific)', group: 'deal' },
  { key: 'set_start_time', label: 'Set start (performance, else event; 12h Pacific)', group: 'deal' },
  { key: 'set_end_time', label: 'Set end (performance, else event; 12h Pacific)', group: 'deal' },
  { key: 'set_duration', label: 'Set duration (computed, pricing hours, or venue set_length)', group: 'deal' },
  { key: 'set_duration_hours', label: 'Set duration as decimal hours (e.g. 2.5)', group: 'deal' },
  { key: 'balance_amount', label: 'Balance due (currency; same as balance_amount_display)', group: 'deal' },
  { key: 'balance_amount_numeric', label: 'Balance due raw number (no currency symbol)', group: 'deal' },
  { key: 'balance_amount_display', label: 'Balance due (currency)', group: 'deal' },
  { key: 'remaining_balance', label: 'Same as balance_amount (alias)', group: 'deal' },
  { key: 'remaining_balance_display', label: 'Same as balance_amount_display (alias)', group: 'deal' },
  { key: 'onsite_contact_name', label: 'On-site contact name', group: 'deal' },
  { key: 'onsite_contact_role', label: 'On-site contact role', group: 'deal' },
  { key: 'onsite_contact_email', label: 'On-site contact email', group: 'deal' },
  { key: 'onsite_contact_phone', label: 'On-site contact phone', group: 'deal' },
  { key: 'onsite_contact_phone_display', label: 'On-site contact phone (formatted)', group: 'deal' },
  { key: 'onsite_contact_company', label: 'On-site contact company', group: 'deal' },
  { key: 'deal_event_date', label: 'Deal event date (long form when YYYY-MM-DD)', group: 'deal' },
  { key: 'deal_event_date_iso', label: 'Deal event date ISO YYYY-MM-DD', group: 'deal' },
  { key: 'gross_amount', label: 'Gross amount', group: 'deal' },
  { key: 'gross_amount_display', label: 'Gross amount (currency)', group: 'deal' },
  { key: 'full_fee_display', label: 'Full performance fee (currency; same as gross)', group: 'deal' },
  { key: 'cancellation_full_fee_display', label: 'Cancellation full fee (currency; same as gross)', group: 'deal' },
  { key: 'contract_fee_display', label: 'Contract / total fee (currency; same as gross)', group: 'deal' },
  { key: 'commission_rate', label: 'Commission rate (percent, matches Earnings)', group: 'deal' },
  { key: 'commission_rate_fraction', label: 'Commission rate (decimal, e.g. 0.2)', group: 'deal' },
  { key: 'commission_amount', label: 'Commission amount', group: 'deal' },
  { key: 'commission_amount_display', label: 'Commission amount (currency)', group: 'deal' },
  { key: 'commission_tier', label: 'Commission tier (includes Artist network = no booking commission)', group: 'deal' },
  { key: 'payment_due_date', label: 'Payment due date', group: 'deal' },
  { key: 'agreement_url', label: 'Agreement URL', group: 'deal' },
  { key: 'deal_notes', label: 'Deal notes', group: 'deal' },
  {
    key: 'pricing_summary_text',
    label: 'Pricing summary (from deal calculator; empty if no snapshot)',
    group: 'deal',
  },
  {
    key: 'pricing_total_display',
    label: 'Pricing total — currency (from snapshot)',
    group: 'deal',
  },
  {
    key: 'pricing_deposit_display',
    label: 'Pricing deposit — currency (from snapshot)',
    group: 'deal',
  },
  {
    key: 'pricing_engagement_scope_paragraph',
    label: 'Fee scope — professional engagement (prep, production, performance; not “hourly only”)',
    group: 'deal',
  },
  {
    key: 'pricing_additional_time_paragraph',
    label: 'Extended / additional performance time (dynamic rate when catalog + snapshot)',
    group: 'deal',
  },
  {
    key: 'pricing_client_facing_fee_paragraph',
    label: 'Combined fee explainer (scope + structure + add-ons + extended time)',
    group: 'deal',
  },
  { key: 'pricing_base_structure_line', label: 'How the quote is structured (package or hourly line)', group: 'deal' },
  { key: 'pricing_fee_basis_note', label: 'Short note: calculator vs manually agreed total', group: 'deal' },
  { key: 'pricing_booked_hours_display', label: 'Performance hours entered on the deal', group: 'deal' },
  { key: 'pricing_billable_hours_display', label: 'Billable hours (max of booked and catalog minimum)', group: 'deal' },
  { key: 'pricing_minimum_billable_hours_display', label: 'Catalog minimum billable hours (if any)', group: 'deal' },
  { key: 'pricing_minimum_hours_note', label: 'Note when minimum billable hours apply', group: 'deal' },
  { key: 'pricing_reference_hourly_display', label: 'Reference hourly rate (primary or overtime service)', group: 'deal' },
  { key: 'pricing_overtime_rate_display', label: 'Additional-time hourly rate (when per-hour overtime applies)', group: 'deal' },
  { key: 'pricing_primary_service_name', label: 'Primary pricing service name', group: 'deal' },
  { key: 'pricing_primary_rate_display', label: 'Primary service rate (hourly or flat)', group: 'deal' },
  { key: 'pricing_package_name', label: 'Package name (package-based quotes)', group: 'deal' },
  { key: 'pricing_package_hours_included', label: 'Hours included in package', group: 'deal' },
  { key: 'pricing_package_price_display', label: 'Package base price (currency)', group: 'deal' },
  { key: 'pricing_addons_line', label: 'Add-ons and surcharges (names, from snapshot + catalog)', group: 'deal' },
  { key: 'pricing_discounts_line', label: 'Discounts applied (names)', group: 'deal' },
  {
    key: 'pricing_fee_transparency_table_html',
    label: 'Fee breakdown table (HTML; app-generated; scope / bundled ops / total)',
    group: 'deal',
  },
  {
    key: 'pricing_fee_transparency_plain',
    label: 'Fee breakdown (plain lines: scope, optional bundle, total)',
    group: 'deal',
  },
  { key: 'pricing_fee_scope_amount_display', label: 'Performance & agreed scope — amount (USD, whole dollars)', group: 'deal' },
  {
    key: 'pricing_fee_operations_bundle_amount_display',
    label: 'Production & compliance bundle — amount (empty if under $1 delta)',
    group: 'deal',
  },
  { key: 'pricing_fee_total_display', label: 'Contract total from deal gross (USD, whole dollars)', group: 'deal' },
  {
    key: 'pricing_fee_breakdown_note',
    label: 'Note when contract gross differs from saved quote total',
    group: 'deal',
  },

  { key: 'contact_name', label: 'Contact name', group: 'contact' },
  { key: 'contact_role', label: 'Contact role', group: 'contact' },
  { key: 'contact_email', label: 'Contact email', group: 'contact' },
  { key: 'contact_phone', label: 'Contact phone', group: 'contact' },
  { key: 'contact_phone_display', label: 'Contact phone (formatted)', group: 'contact' },
  { key: 'contact_company', label: 'Contact company', group: 'contact' },
  { key: 'client_name', label: 'Client / counterparty name (alias)', group: 'contact' },
  { key: 'client_role', label: 'Client role (alias)', group: 'contact' },
  { key: 'client_email', label: 'Client email (alias)', group: 'contact' },
  { key: 'client_phone', label: 'Client phone (alias)', group: 'contact' },
  { key: 'client_phone_display', label: 'Client phone formatted (alias)', group: 'contact' },
  { key: 'client_company', label: 'Client company (alias)', group: 'contact' },

  { key: 'artist_name', label: 'Artist name', group: 'artist' },
  { key: 'company_name', label: 'Company name (Settings; else contact company)', group: 'artist' },
  { key: 'tagline', label: 'Tagline', group: 'artist' },
  { key: 'website', label: 'Website', group: 'artist' },
  { key: 'phone', label: 'Phone (raw from Settings)', group: 'artist' },
  { key: 'phone_display', label: 'Phone (formatted for documents)', group: 'artist' },
  { key: 'social_handle', label: 'Social handle', group: 'artist' },
  { key: 'reply_to_email', label: 'Reply-to email', group: 'artist' },
  { key: 'artist_email', label: 'Artist email', group: 'artist' },
  { key: 'manager_name', label: 'Manager name', group: 'artist' },
  { key: 'manager_email', label: 'Manager email', group: 'artist' },
  { key: 'manager_phone', label: 'Manager phone (formatted)', group: 'artist' },
  { key: 'manager_phone_display', label: 'Manager phone (formatted; alias)', group: 'artist' },
  { key: 'from_email', label: 'From email', group: 'artist' },
]

export function catalogKeysUnion(templateExtraKeys: string[]): string[] {
  const fromCatalog = AGREEMENT_VARIABLE_CATALOG.map(e => e.key)
  return [...new Set([...fromCatalog, ...templateExtraKeys])].sort((a, b) =>
    a.localeCompare(b)
  )
}
